
LoGS.pdf: LoGS.texinfo
	pdftex LoGS.texinfo
	texindex LoGS.??
	pdftex LoGS.texinfo

clean: 
	rm -rf LoGS.aux LoGS.cp LoGS.fn LoGS.ky LoGS.log LoGS.pdf LoGS.pg LoGS.toc LoGS.tp LoGS.vr \#LoGS.texinfo# LoGS.info LoGS.texinfo~ LoGS.cp LoGS.fn LoGS.cps LoGS.fns LoGS.kys LoGS.pgs LoGS.tps LoGS.vrs
